### ISSUE TITLE
Is there a way to easily reproduce the paper using this implementation?

### ISSUE THREAD

**Issue by hereismari** [Newcomer520/tf-dagmm#1]
Hi,

Is there a way to easily reproduce the paper using this implementation? Using the datasets mentioned in the paper and getting the same metrics.

**Comment by Newcomer520** [comment]
Hello,
Unfortunately I build the convolutional autoencoder to analyze the data of images. I think it should take a while to modify the codebase in order to reproduce the results in the paper.

**Comment by hereismari** [comment]
Thanks for the quick answer!
